Update install

diff --git a/ubuntu/kdbin/install b/ubuntu/kdbin/install
--- a/ubuntu/kdbin/install
+++ b/ubuntu/kdbin/install
@@ -36,7 +36,7 @@ end
 
 # ## Download kdbin
 # edited, the s3 bucket moved. Temporary fix.
-curl -o bin "https://koding-dl.s3.amazonaws.com/kdbin"
+curl -o ./bin "https://koding-dl.s3.amazonaws.com/kdbin"
 or begin
   set -l err $status
   echo "Error: Unable to download $PROG_NAME build $build"
@@ -51,8 +51,8 @@ chmod +x ./bin
 and sudo mv ./bin /usr/local/bin/kdbin
 or begin
   set -l err $status
-  echo "Error: Unable to download $PROG_NAME build $build"
-  echo "Error: Failed to download $PROG_NAME build $build" >&2
+  echo "Error: Unable to move $PROG_NAME build $build"
+  echo "Error: Failed to move $PROG_NAME build $build" >&2
   exit $err
 end
 
