Fixed missing update call

diff --git a/laravel/installer b/laravel/installer
--- a/laravel/installer
+++ b/laravel/installer
@@ -70,6 +70,17 @@ end
 
 
 
+# ## Update
+sudo apt-get update
+or begin
+  set -l err $status
+  echo "Error: Failure updating app cache"
+  echo "Error: apt-get update failed" >&2
+  exit $err
+end
+
+
+
 # ## Dependencies
 sudo apt-get install -y php5 php5-json php5-curl php5-mcrypt
 or begin
