Added Oracle7, and added requirement to ElasticSearch

diff --git a/elasticsearch/installer b/elasticsearch/installer
--- a/elasticsearch/installer
+++ b/elasticsearch/installer
@@ -2,7 +2,7 @@
 function main
 # ## Config
 set -l PROG_NAME    "Elasticsearch"
-set -l REQ_STORAGE  469920
+set -l REQ_STORAGE  29136
 set -l USERNAME     $USER
 set -l DEBIAN       "elasticsearch-1.4.2.deb"
 
@@ -18,6 +18,19 @@ from the following URL:
     $USERNAME.koding.io:9200
 "
   echo "Req Error: Already installed" >&2
+  exit 1
+end
+# ### Oracle Java7 Installed?
+java -version 2>| grep -iq "se runtime"
+and java -version 2>| grep -iq "1.7"
+or begin
+  echo "
+$PROG_NAME requires Oracle Java7 to be installed. You can install it
+with the following command:
+
+    \$ kpm install oracle-java7
+"
+  echo "Req Error: Installation not found" >&2
   exit 1
 end
 # ### User not root
@@ -52,48 +65,6 @@ Please refer to the following guide for tips on how to free up VM storage:
 "
   echo "Req Error: Not enough storage" >&2
   exit 1
-end
-
-
-
-# ## Oracle PPA
-sudo add-apt-repository -y ppa:webupd8team/java
-or begin
-  set -l err $status
-  echo "Error: Failed to add oracle repository"
-  echo "Error: Failed to add ppa:webupd8team/java" >&2
-  exit $err
-end
-
-
-
-# ## Update
-# This message is here due to a pause on apt-get update that might
-# confuse the user. A vague message will help them know that it isn't
-# froze.
-echo -e "\nUpdating.."
-sudo apt-get update
-or begin
-  set -l err $status
-  echo "Error: Failed to update package list"
-  echo "Error: apt-get update failed" >&2
-  exit $err
-end
-
-
-
-# ## Allow non-interactive installation
-echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
-
-
-
-# ## Install dependencies
-sudo apt-get install -y oracle-java7-installer
-or begin
-  set -l err $status
-  echo "Error: Failure installing $PROG_NAME dependencies"
-  echo "Error: apt-get failed to install dependencies" >&2
-  exit $err
 end
 
 
