Removed Symlinks
It seems that Github doesn't support Symlinks in their web ui, so
older versions of KPM looking at the symlink location would not be
forwarded to the proper file. As such, i'm restoring the old files.

These will be duplicates unfortunately, but we'll phase out old kpm
versions.

diff --git a/installers/composer b/installers/composer
--- a/installers/composer
+++ b/installers/composer
@@ -1,1 +1,64 @@
-../composer/installer
+#!/usr/bin/env fish
+function main
+# ## Config
+set -l PROG_NAME    "Composer"
+set -l USERNAME     $USER
+
+
+
+# ## Check Requirements
+# ### Already installed?
+if which composer > /dev/null
+  echo "
+$PROG_NAME is already installed. You can access it by running the
+following command:
+
+    \$ composer
+"
+  echo "Req Error: Already installed" >&2
+  exit 1
+end
+# ### php installed?
+if not which php > /dev/null
+  echo "
+$PROG_NAME requires that php is already installed. Please install php
+first.
+"
+  echo "Req Error: php not installed" >&2
+  exit 1
+end
+
+
+
+# ## Install
+curl -sS https://getcomposer.org/installer | sudo php -- \
+  --filename=composer \
+  --install-dir=/usr/local/bin \
+  --quiet
+or begin
+  set -l err $status
+  echo "Error: Failure installing $PROG_NAME"
+  echo "Error: curl and php failed to install $PROG_NAME" >&2
+  exit $err
+end
+
+
+
+# ## Add bin path
+# TODO: Add bin to path
+# Not sure what the best way is to do this yet,
+# since this involves the users shell and environment.
+
+
+
+# ## Success
+echo "
+$PROG_NAME installation complete. You can access it by running the
+following command:
+
+    \$ composer
+"
+end
+main
+# vim: set filetype=fish:
+
diff --git a/installers/mean b/installers/mean
--- a/installers/mean
+++ b/installers/mean
@@ -1,1 +1,123 @@
-../mean/installer
+#!/usr/bin/env fish
+function main
+
+# ## Config
+set -l PROG_NAME    "Mean"
+set -l REQ_STORAGE  120508
+set -l USERNAME     $USER
+
+# ## Check Requirements
+# ### Storage
+set -l available_storage (df / | awk 'NR>1{print $4}')
+if test (math $available_storage - $REQ_STORAGE) -lt 0
+  set -l hReq (math $REQ_STORAGE / 1024)
+  set -l hAvl (math $available_storage / 1024)
+  echo "
+$PROG_NAME requires at least $hReq""MB storage, \
+and you have $hAvl""MB free.
+
+Please free up some space, and try again. You can start by deleting any
+large files or directories in your home directory or delete software that
+you do not need.
+
+You can also upgrade your account to get more space, at the following url
+
+    https://koding.com/Pricing
+"
+  echo "Req Error: Not enough storage" >&2
+  exit 1
+end
+
+# ### Check if already installed
+if which mean > /dev/null
+  echo "
+$PROG_NAME is already installed. It can be started with the following \
+command:
+
+    \$ mean myApp
+"
+  echo "Req Error: Already installed" >&2
+  exit 1
+end
+
+# ### Check if node is installed
+if not which node > /dev/null
+  echo "
+$PROG_NAME requires that NodeJS is already installed. Please
+install it first.
+"
+  echo "Req Error: Missing npm" >&2
+  exit 1
+end
+
+# ## Check if npm installed
+if not which npm > /dev/null
+  echo "
+$PROG_NAME requires that npm is already installed. Please install
+npm first.
+"
+  echo "Req Error: Missing npm" >&2
+  exit 1
+end
+
+# ## Check if mongodb installed
+if not which mongo > /dev/null
+  echo "
+$PROG_NAME requires that mongodb is already installed. Please install
+mongo first.
+"
+  echo "Req Error: Missing mongodb" >&2
+  exit 1
+end
+
+
+# ## Check if Grunt installed
+if not which grunt > /dev/null
+  echo "
+$PROG_NAME requires that grunt is already installed. Please install
+grunt first.
+"
+  echo "Req Error: Missing grunt" >&2
+  exit 1
+end
+
+
+
+# ## Install
+# ### build-essential - These will be needed for the user to npm install a mean project without getting bson errors
+sudo apt-get install -y gcc make build-essential
+or begin
+  set -l err $status
+  echo "Error: Failure installing apt dependencies"
+  echo "Error: Failure installing gcc, make, build-essential" >&2
+  exit $err
+end
+
+
+
+# ### mean
+sudo npm install -g mean-cli
+or begin
+  set -l err $status
+  echo "Error: Failure installing $PROG_NAME"
+  echo "Error: npm failed to install $PROG_NAME" >&2
+  exit $err
+end
+
+
+
+# ## Complete
+echo "
+Installation complete, and $PROG_NAME is now available.
+
+To create a project:
+
+    \$ mean init <myApp>
+    \$ cd <myApp> && npm install
+
+"
+
+
+end
+main
+# vim: set filetype=fish:
diff --git a/installers/mean-io-stack b/installers/mean-io-stack
--- a/installers/mean-io-stack
+++ b/installers/mean-io-stack
@@ -1,1 +1,74 @@
-../mean-io-stack/installer
+#!/usr/bin/env fish
+function main
+
+# ## Config
+set -l PROG_NAME    "Mean.io Stack"
+set -l REQ_STORAGE  765628
+set -l USERNAME     $USER
+
+# ## Set installs in this bundle
+set -l bundled mongodb grunt mean
+set -l mongodb "mongod"
+set -l grunt "grunt"
+set -l mean "mean"
+set -l installed
+
+# ## Check Requirements
+# ### Storage
+set -l available_storage (df / | awk 'NR>1{print $4}')
+if test (math $available_storage - $REQ_STORAGE) -lt 0
+  set -l hReq (math $REQ_STORAGE / 1024)
+  set -l hAvl (math $available_storage / 1024)
+  echo "
+$PROG_NAME requires at least $hReq""MB storage, \
+and you have $hAvl""MB free.
+
+Please free up some space, and try again. You can start by deleting any
+large files or directories in your home directory or delete software that
+you do not need.
+
+You can also upgrade your account to get more space, at the following url
+
+    https://koding.com/Pricing
+
+"
+  echo "Req Error: Not enough storage" >&2
+  exit 1
+end
+
+# ## Install everything in the bundle
+for bundle in $bundled
+	if not set -q failed
+		if not which $$bundle > /dev/null
+   		 	echo "Installing $bundle"
+			kpm install $bundle
+   		 	#fish ./$bundle
+			if not which $$bundle > /dev/null
+				set -l failed
+			else
+				set installed  $installed  $bundle
+			end
+		else
+   			echo "$bundle already installed, skipping."
+		end
+	end
+end
+
+# ## Revert if any part failed
+if set -q failed
+	echo "One of the bundled installs failed."
+	echo "Reverting all installs performed in this package to return system to original state"
+	for install in $installed
+		echo "reverting $install"
+		kpm uninstall $install
+	end
+end
+
+# ## Complete
+echo "---------------------------------------------------------------------------------"
+echo "Installation complete, all installs in the $PROG_NAME completed successfully.  "
+echo "---------------------------------------------------------------------------------"
+
+end
+main
+# vim: set filetype=fish:
diff --git a/installers/meteor b/installers/meteor
--- a/installers/meteor
+++ b/installers/meteor
@@ -1,1 +1,129 @@
-../meteor/installer
+#!/usr/bin/env fish
+function main
+
+
+# ## Config
+set -l PROG_NAME    "MeteorJS"
+set -l REQ_STORAGE  806128
+set -l USERNAME     $USER
+
+# ## Check Requirements
+# ### Check if it's already installed
+if which meteor > /dev/null
+  echo "
+$PROG_NAME is already installed. To create a $PROG_NAME app, use the meteor
+command as seen below:
+
+    \$ meteor create ~/my_cool_app
+    \$ cd ~/my_cool_app
+    \$ meteor
+
+Or see the docs at:
+
+    http://docs.meteor.com
+"
+  echo "Req Error: Already installed" >&2
+  exit 1
+end
+# ### User not root
+# Ensure that the user is not `root`, because the default Apache
+# web directory is /home/user/Web, where as root would
+# install it to /root/Web
+if test "$USERNAME" = "root"
+  echo "
+$PROG_NAME should not be installed from the root user. Please switch
+to your normal Koding user, and try this command again.
+"
+  echo "Req Error: Logged in as root" >&2
+  exit 1
+end
+# ### Storage
+set -l available_storage (df / | awk 'NR>1{print $4}')
+if test (math $available_storage - $REQ_STORAGE) -lt 0
+  echo "
+$PROG_NAME requires at least "(math $REQ_STORAGE / 1024)"MB storage, \
+and you have "(math $available_storage / 1024)"MB free.
+
+Please free up some space, and try again. You can start by deleting any
+large files or directories in your home directory or delete software
+that you do not need.
+
+You can also upgrade your account to get more space, at the following url
+
+    https://koding.com/Pricing
+
+Please refer to the following guide for tips on how to free up VM storage:
+
+    http://learn.koding.com/guides/freeing-up-space
+"
+  echo "Req Error: Not enough storage" >&2
+  exit 1
+end
+
+
+
+# ## Download
+echo "
+Downloading Meteor
+"
+mkdir -p /tmp
+curl --progress-bar --fail -o "/tmp/meteor.tar.gz" \
+  "https://d3sqy0vbqsdhku.cloudfront.net/packages-bootstrap/1.0/meteor-bootstrap-os.linux.x86_64.tar.gz"
+or begin
+  set -l err $status
+  echo "Error: Download of MeteorJS failed"
+  echo "Error: Download of MeteorJS failed" >&2
+  exit $err
+end
+
+
+
+# ## Unzip archive
+tar -C ~ -xzf "/tmp/meteor.tar.gz"
+or begin
+  set -l err $status
+  echo "Error: Extracting MeteorJS failed"
+  echo "Error: Extracting MeteorJS failed" >&2
+  exit $err
+end
+
+
+
+# ## Link bin
+sudo ln -s ~/.meteor/meteor /usr/local/bin/meteor
+or begin
+  set -l err $status
+  echo "Error: Linking meteor bin failed"
+  echo "Error: Linking meteor bin failed" >&2
+  exit $err
+end
+
+
+
+
+# ## Cleanup temp files
+rm -f "/tmp/meteor.tar.gz"
+# I don't believe -f can even throw a non-zero exit
+
+
+
+# ## End message
+echo "
+Installation complete.
+
+To create a meteor app, use the meteor command as seen below:
+
+    \$ meteor create ~/my_cool_app
+    \$ cd ~/my_cool_app
+    \$ meteor
+
+Or see the docs at:
+
+    http://docs.meteor.com
+"
+
+
+end
+main
+
+# vim: set filetype=fish:
diff --git a/installers/rails b/installers/rails
--- a/installers/rails
+++ b/installers/rails
@@ -1,1 +1,127 @@
-../rails/installer
+#!/usr/bin/env fish
+function main
+
+
+
+# ## Config
+set -l PROG_NAME    "Rails"
+set -l REQ_STORAGE  4764
+set -l USERNAME     $USER
+
+
+
+# ## Check Requirements
+# ## Check if root
+if test "$USERNAME" = "root"
+  echo "
+$PROG_NAME should not be installed from the root user. Please switch
+to your normal Koding user, and try this command again.
+"
+  echo "Req Error: Logged in as root" >&2
+  exit 1
+end
+# ### Check if already installed
+if which rails > /dev/null
+  echo "
+$PROG_NAME is already installed. To create and start a rails app, run
+the following commands:
+
+    \$ rails new myApp
+    \$ cd myApp
+    \$ rails server -b 0.0.0.0
+
+You can then visit your app on the following address:
+
+    $USERNAME.koding.io:8448
+
+"
+  echo "Req Error: Rails already installed" >&2
+  exit 1
+end
+# ### Check if ruby is installed
+if not which ruby > /dev/null
+  echo "
+$PROG_NAME requires that Ruby is already installed. Please install it
+first.
+"
+  echo "Req Error: Missing ruby" >&2
+  exit 1
+end
+# ### Storage
+set -l available_storage (df / | awk 'NR>1{print $4}')
+if test (math $available_storage - $REQ_STORAGE) -lt 0
+  echo "
+$PROG_NAME requires at least "(math $REQ_STORAGE / 1024)"MB storage, \
+and you have "(math $available_storage / 1024)"MB free.
+
+Please free up some space, and try again. You can start by deleting any large
+files or directories in your home directory or delete software that you do
+not need.
+
+You can also upgrade your account to get more space, at the following url
+
+    https://koding.com/Pricing
+
+Please refer to the following guide for tips on how to free up VM storage:
+
+    http://learn.koding.com/guides/freeing-up-space
+"
+  echo "Req Error: Not enough storage" >&2
+  exit 1
+end
+
+
+
+# ## Update
+sudo apt-get update -y
+or begin
+  set -l err $status
+  echo "Error: Failure updating apt"
+  echo "Error: apt-get update failed" >&2
+  exit $err
+end
+
+
+
+# ## Install dependencies
+sudo apt-get install -y build-essential ruby-dev libsqlite3-dev
+or begin
+  set -l err $status
+  echo "Error: Failure installing dependencies"
+  echo "Error: apt-get install failed" >&2
+  exit $err
+end
+
+
+
+# ## Install
+sudo gem install rails --no-ri --no-rdoc
+or begin
+  set -l err $status
+  echo "Error: Failure installing rails"
+  echo "Error: gem install failed" >&2
+  exit $err
+end
+
+
+
+# ## End
+echo "
+$PROG_NAME Installation complete! To create and start a rails app, run
+the following commands:
+
+    \$ rails new myApp
+    \$ cd myApp
+    \$ rails server -b 0.0.0.0
+
+You can then visit your app on the following address:
+
+    $USERNAME.koding.io:8448
+
+"
+
+
+
+end
+main
+# vim: set filetype=fish:
diff --git a/uninstallers/codeigniter b/uninstallers/codeigniter
--- a/uninstallers/codeigniter
+++ b/uninstallers/codeigniter
@@ -1,1 +1,72 @@
-../codeigniter/uninstaller
+#!/usr/bin/env fish
+function main
+
+
+
+# ## Config
+set -l PROG_NAME    "Codeigniter"
+set -l USERNAME     $USER
+set -l INSTALL_LOC  ~/Web/codeigniter
+
+
+
+# ## Check Requirements
+# ### Is it installed?
+if not test -e "$INSTALL_LOC"
+  echo "Error: A $PROG_NAME installation in the default kpm install
+location cannot be found."
+  echo "Req Error: Cannot find install" >&2
+  exit 1
+end
+
+
+
+# ## Confirm
+echo "
+By uninstalling $PROG_NAME, you will FULLY DELETE the kpm installation of
+$PROG_NAME. This includes any data found within the following directory.
+
+    $INSTALL_LOC
+
+This cannot be undone.
+
+Are you sure?
+"
+for x in (seq 3)
+  echo -n "(yes/no, y/n) "
+  read -l confirm < /dev/tty
+  or begin
+    echo "Input Error: Empty confirm response" >&2
+    exit 1
+  end
+  switch "$confirm"
+    case "yes" "y"
+      break
+    case "no" "n"
+      echo "Confirm choice no" >&2
+      exit 1
+    case "*"
+      if test "$x" -eq 3
+        echo -e "\nAborting after 3 failed attempts"
+        exit 1
+      else
+        echo -e "\nInvalid response, please retry."
+      end
+  end
+end
+
+
+
+# ## Remove
+rm -rf $INSTALL_LOC
+# I don't think it's possible for `rm -rf` to return a non-zero
+
+
+
+# ## Success
+echo "
+$PROG_NAME has been uninstalled successfully.
+"
+end
+main
+# vim: set filetype=fish:
diff --git a/uninstallers/redis b/uninstallers/redis
--- a/uninstallers/redis
+++ b/uninstallers/redis
@@ -1,1 +1,38 @@
-../redis/uninstaller
+#!/usr/bin/env fish
+function main
+# ## Config
+set -l PROG_NAME    "Redis"
+set -l USERNAME     $USER
+
+
+
+# ## Check Requirements
+# ### Check if installed
+if not which redis-server > /dev/null
+  echo "
+An installation of $PROG_NAME cannot be found.
+"
+  echo "Req Error: Installation not found" >&2
+  exit 1
+end
+
+
+
+# ## Uninstall
+sudo apt-get purge --auto-remove -y redis-server
+or begin
+  set -l err $status
+  echo "Error: Failed to uninstall $PROG_NAME"
+  echo "Error: apt-get purge failed" >&2
+  exit $err
+end
+
+
+
+# ## Success
+echo "
+$PROG_NAME has been uninstalled successfully.
+"
+end
+main
+# vim: set filetype=fish:
