Added update to pip installer
This was required if the KDVM had not been updated yet.

diff --git a/installers/pip b/installers/pip
--- a/installers/pip
+++ b/installers/pip
@@ -21,6 +21,17 @@ end
 
 
 
+# ## Update
+sudo apt-get update
+or begin
+  set -l err $status
+  echo "Error: Failure updating"
+  echo "Error: apt-get update failed" >&2
+  exit $err
+end
+
+
+
 # ## Install
 sudo apt-get install -y python-pip
 or begin
