Improved the general consistency (consistency/etc) with jekyll

diff --git a/ubuntu/jekyll/install b/ubuntu/jekyll/install
--- a/ubuntu/jekyll/install
+++ b/ubuntu/jekyll/install
@@ -1,12 +1,13 @@
 #!/bin/bash
+function main() {
 
-# Config
+# ## Config
 PROG_NAME="Jekyll"
 REQ_STORAGE=237000
 USERNAME=$USER
 
 
-# Check if it's installed
+# ## Check if it's installed
 if [ $(which jekyll) > /dev/null ]; then
   echo "
 $PROG_NAME is already installed. If you need to start it, run the
@@ -25,7 +26,7 @@ Then navigate to:
 fi
 
 
-# Check if the user is `root`
+# ## Check if the user is `root`
 if [ $USERNAME == "root" ]; then
   echo "
 $PROG_NAME should not be installed from the root user. Please switch
@@ -36,9 +37,25 @@ to your normal Koding user, and try this command again.
 fi
 
 
-# Check if there's not enough storage
-available_storage=$(df / | awk 'NR>1{print $4}')
+# ## Check if gem is installed
+# Note that we don't require ruby2, but at the time of writing this
+# script there is no plain ruby installer, just ruby2.
+if ! which gem >/dev/null; then
+  cat << EOF
 
+The kpm version of $PROG_NAME requires that Ruby & Gem are already
+installed.  Please install it with the following command:
+
+    \$ kpm install ruby2
+
+EOF
+  echo "Req Error: Missing gem" >&2
+  exit 84
+fi
+
+
+# ## Check if there's not enough storage
+available_storage=$(df / | awk 'NR>1{print $4}')
 if (($available_storage < $REQ_STORAGE)); then
   echo "
 $PROG_NAME requires at least "$(expr $REQ_STORAGE / 1024)"MB storage, \
@@ -61,8 +78,50 @@ Please refer to the following guide for tips on how to free up VM storage:
 fi
 
 
-# Download RVM and Jekyll
-gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
-\curl -sSL https://get.rvm.io | bash -s stable --ruby
-source .rvm/scripts/rvm
-gem install jekyll
+
+# ## Update
+# This message is here due to a pause on apt-get update that might
+# confuse the user. A vague message will help them know that it isn't
+# froze.
+echo "Updating.."
+sudo apt-get update
+err=$?; if [ "$err" -ne 0 ]; then
+  echo "Error: Failed to update package list"
+  echo "Error: apt-get update failed" >&2
+  exit $err
+fi
+
+
+
+# ## Install
+sudo apt-get install -y make
+err=$?; if [ "$err" -ne 0 ]; then
+  echo "Error: Failure installing $PROG_NAME"
+  echo "Error: apt-get failed to install" >&2
+  exit $err
+fi
+
+
+# ## Install jekyll
+sudo gem install jekyll
+err=$?; if [ "$err" -ne 0 ]; then
+  echo "Error: Failed to install jekyll"
+  echo "Error: gem failed to install jekyll" >&2
+  exit $err
+fi
+
+
+# ## Success
+cat << EOF
+
+$PROG_NAME installation complete. To create a new $PROG_NAME server and
+start it, run the following commands:
+
+  \$ jekyll new JekyllSite
+  \$ cd JekyllSite
+  \$ jekyll serve --host 0.0.0.0
+
+EOF
+
+}
+main
diff --git a/ubuntu/jekyll/uninstall b/ubuntu/jekyll/uninstall
--- a/ubuntu/jekyll/uninstall
+++ b/ubuntu/jekyll/uninstall
@@ -1,9 +1,9 @@
 #!/bin/bash
+function main() {
 
 # Config
 PROG_NAME="Jekyll"
 USERNAME=$USER
-
 
 # Check if it's installed
 if ! [ $(which jekyll) > /dev/null ]; then
@@ -14,25 +14,18 @@ A kpm installation of $PROG_NAME cannot be found.
   exit 84
 fi
 
-
 # Remove RVM & Jekyll
-gem uninstall jekyll --force
-rvm implode --force
-
-rm -f ~/.bashrc
-rm -f ~/.mkshrc
-rm -f ~/.zshrc
-rm -f ~/.bash_profile
-rm -f ~/.profile
-rm -f ~/.zlogin
-
-# Remove keys
-rm -rf ~/.gnupg
-
-# Remove gems that were installed along with jekyll
-rm -rf ~/.gem
+sudo gem uninstall jekyll
+err=$?; if [ "$err" -ne 0 ]; then
+  echo "Error: Failed to remove jekyll"
+  echo "Error: Gem failed to remove jekyll"
+  exit $err
+fi
 
 # Success
 echo "
 $PROG_NAME has been uninstalled successfully.
 "
+
+}
+main
