Updated to rails2.0, added a couple rails dependencies

diff --git a/rails/installer b/rails/installer
--- a/rails/installer
+++ b/rails/installer
@@ -84,7 +84,8 @@ end
 
 
 # ## Install dependencies
-sudo apt-get install -y build-essential ruby-dev libsqlite3-dev
+sudo apt-get install -y build-essential libsqlite3-dev \
+  ruby2.0 ruby2.0-dev libssl-dev zlib1g-dev
 or begin
   set -l err $status
   echo "Error: Failure installing dependencies"
@@ -94,7 +95,20 @@ end
 
 
 
+# ## Make 2.0 the default
+sudo ln -sf /usr/bin/ruby2.0 /usr/bin/ruby
+and sudo ln -sf /usr/bin/gem2.0 /usr/bin/gem
+or begin
+  set -l err $status
+  echo "Error: Failed to set ruby2.0 to default"
+  echo "Error: Failed to set ruby2.0 and gem2.0 to default" >&2
+  exit $err
+end
+
+
+
 # ## Install
+echo "Installing rails, this can take a while.."
 sudo gem install rails --no-ri --no-rdoc
 or begin
   set -l err $status
diff --git a/rails/uninstaller b/rails/uninstaller
--- a/rails/uninstaller
+++ b/rails/uninstaller
@@ -36,11 +36,24 @@ end
 # Note that we're not purging all dependencies, since some things
 # (like build-essentials) *may* be required by other programs. We're
 # only removing what we're resonable sure that isn't required.
-sudo apt-get purge -y ruby-dev libsqlite3-dev
+sudo apt-get purge -y libsqlite3-dev \
+  ruby2.0 ruby2.0-dev libssl-dev zlib1g-dev
 or begin
   set -l err $status
   echo "Error: Failure installing dependencies"
   echo "Error: apt-get install failed" >&2
+  exit $err
+end
+
+
+
+# ## Restore
+sudo ln -sf /usr/bin/ruby1.9.1 /usr/bin/ruby
+and sudo ln -sf /usr/bin/gem1.9.1 /usr/bin/gem
+or begin
+  set -l err $status
+  echo "Error: Failed to restore ruby default"
+  echo "Error: Failed to make ruby1.9.1 the default" >&2
   exit $err
 end
 
